---
title: "10-load-data"
output: html_notebook
---

The purpose of this notebook is to load and clean the data.  It should also test the data (e.g., by assertr) to ensure that assumptions about the data are met, and store the cleaned and tested data.

```{r}
#Import helpful packages
library(haven)
library(vroom)
library(boxr)
library(janitor)
library(assertr)
library(tidyverse)
library(batman)
library(dplyr)
```
# set working directory
setwd('~/Documents/AncientArtifacts/ancient-artifacts')

# read in each csv file into data frames
LithicData <- read_csv("LithicExperimentalData.csv")
ASData <- read_csv("ArchaeologicalSoilData.csv")

# clean up first row of data
LithicData <- LithicData[-c(1),]
ASData <- ASData[-c(1),]

# join data frames and clean column names
ArtifactData <- rbind(LithicData,ASData) %>%
  janitor::clean_names() 
 
ArtifactData <- mutate(ArtifactData, file_id = NA)

# move file name to first column in data frame
ArtifactData <- select(ArtifactData, file_id, everything())

#convert filters to logicals
ArtifactData$filter0 <- batman::to_logical(ArtifactData$filter0, custom_false = c("Reject"))
ArtifactData$filter1 <- batman::to_logical(ArtifactData$filter1, custom_false = c("Reject"))
ArtifactData$filter2 <- batman::to_logical(ArtifactData$filter2, custom_false = c("Reject"))
ArtifactData$filter3 <- batman::to_logical(ArtifactData$filter3, custom_false = c("Reject"))
ArtifactData$filter4 <- batman::to_logical(ArtifactData$filter4, custom_false = c("Reject"))
ArtifactData$filter5 <- batman::to_logical(ArtifactData$filter5, custom_false = c("Reject"))
ArtifactData$filter6 <- batman::to_logical(ArtifactData$filter6, custom_false = c("Reject"))
ArtifactData

# Here we will start writing asserts to validate the data.

# Angularity: 0 (perfect circle)-180 (many sharp edges)
assert(ArtifactData, within_bounds(0,180), angularity, 
       description = "Values must be within 0-180 range.")

# Circularity: 0-1 (perfect circle)
assert(ArtifactData, within_bounds(0,1), circularity,
       description = "Values must be within 0-1 range.")

# Solidity: 0-1 (very smooth surface)
assert(ArtifactData, within_bounds(0,1), solidity,
       description = "Values must be within 0-1 range.")

# Transparency: 0 (least transparent)-1 (most transparent)
assert(ArtifactData, within_bounds(0,1), transparency,
       description = "Values must be within 0-1 range.")

# T/W Ratio: 0-1 (represents a sphere)
assert(ArtifactData, within_bounds(0,1), t_w_ratio,
       description = "Values must be within 0-1 range.")

# Sphericity: 0-1 (perfect circle)
assert(ArtifactData, within_bounds(0,1), sphericity,
       description = "Values must be within 0-1 range.")

# Concavity: 0-1 (rough, spikey surface)
assert(ArtifactData, within_bounds(0,1), concavity,
       description = "Values must be within 0-1 range.")

# Convexity: 0-1 (smooth)
assert(ArtifactData, within_bounds(0,1), convexity,
       description = "Values must be within 0-1 range.")

#L/W Aspect Ratio: 1 (sphere)-infinity
assert(ArtifactData, within_bounds(1,Inf), l_w_ratio,
       description = "Values must be within 1-infinity range.")

# W/T Ratio: 1 (sphere)-infinity
assert(ArtifactData, within_bounds(1,Inf), w_t_ratio,
       description = "Values must be within 1-infinity range.")
